### PR TITLE
Support for SampleReturnCapsule

### PR DESCRIPTION
**Pull request by Breach-Candy**

### CODE REVIEW

**Comment by SirMortimer** [comment]
I think the file name should have the .cfg ending

**Comment by Breach-Candy** [comment]
> I think the file name should have the .cfg ending

I disagree.

**Comment by SirMortimer** [comment]
Where in the tech tree is the sample return capsule unlocked? If it is too soon, the 1MB hdd space might be a bit OP and people might use it instead of, say, the sputnik.

Other than that it looks good to me, waiting for @UsernamesAreAlwaysTaken to make a review (whee, I did't even know that's possible on github :P)

**Comment by Breach-Candy** [comment]
unlocks in survivability. same place as stayputnik iirc

**Comment by SirMortimer** [comment]
if the storage capacity is offset by a higher mass, i'm ok with that.

**Comment by Breach-Candy** [comment]
I'll have to look into it, don't have ksp set up just yet

**Comment by Breach-Candy** [comment]
@SirMortimer alright, had a look into it and it unlocks in landing. Weighs about 100kg. Form factor is the same as stayputnik, only one node on the bottom.

**Comment by SirMortimer** [comment]
One last thing: please add a line to CHANGELOG.md that describes what you've done :)

**Pull request merged**
