### PR TITLE
Chinese correction(incomplete)

### PR DESCRIPTION
**Pull request by tinygrox**
1.Correction
2.Change the display text of celestial bodies from `name` to `displayName`(*Part of localization, if there is a problem, will be reverted*)

### CODE REVIEW

**Comment by SirMortimer** [comment]
Looks good to me. Are you still working on this (because it has 'incomplete' in the title) or can this be merged?

**Comment by tinygrox** [comment]
It is recommended to merge this after the 4.0. There are still some texts that I don't know how to translate at present. I need to get into the game and experience it.

Currently untranslated:
```             #kerbalism-part-plates = Plates
		#kerbalism-part-plates-none = No Plates
		#kerbalism-part-plates-top = Top Only
		#kerbalism-part-plates-bottom = Bottom Only
		#kerbalism-part-plates-top-bottom = Top + Bottom
                #kerbalism-part-left = Left
                #kerbalism-part-right = Right
                #kerbalism-part-front = Front
                #kerbalism-part-back = Back
```

**Comment by gotmachine** [comment]
I really recommend **not doing anything** in regard to localization of the dev/4.0 branch.
Things are likely to change a lot.

**Comment by tinygrox** [comment]
Don't worry, I will keep following.

**Pull request closed without merging**
