### PR TITLE
Clone and fit the launch clamps patch for ReStock

### PR DESCRIPTION
**Pull request by Gordon-Dry**
Cloned from Planner.cfg where it touches stock launch clamp modules.

Module name  is changed
LaunchClamp -> ModuleRestockLaunchClamp

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
I did not want to merge from master - I chose dev for this branch.
What is wrong with GitHub Desktop now?

**Comment by Gordon-Dry** [comment]
For some reason the patch is not applied.
The ReStock patch that changes the module is 
GameData\ReStock\Patches\Structural\restock-structural-launchclamp.cfg
which works FOR[000_ReStock]
and afaik the AFTER[KerbalismDefault] should happen after that?
Or does MM count numbers after characters?

**Comment by Gordon-Dry** [comment]
I found the issue - but first I need to eat.
It's ProcessController with resource = _ECGen instead of a ModuleGenerator ...

**Comment by Gordon-Dry** [comment]
Pfft.
Now the module is correctly added, but toggling the planner consideration on/off in VAB does not change the  shown EC usage.
So I guess the planner does not take the
```
		MODULE
		{
			name = ProcessController
			resource = _ECGen
			title = Power supply
			capacity = 1.0
			running = true
			toggle = false
		}

```in account correctly.

**Comment by Gordon-Dry** [comment]
Excerpt from MM cache for clarification:

```
UrlConfig
{
	parentUrl = Squad/Parts/Utility/launchClamp1/launchClamp1.cfg
	PART
	{
		name = launchClamp1
		module = Part
		author = Andrew Cassidy
		rescaleFactor = 1
		node_attach = 0.0, 1.354437, 0.8069194, 0.0, 0.0, -1.0
		fx_gasBurst_white = 0.0, 1.354437, 0.8369194, 0.0, 0.0, 1.0, activate
		sound_decoupler_fire = activate
		TechRequired = start
		entryCost = 4500
		cost = 200
		category = Structural
		subcategory = 0
		title = TT18-A Launch Stability Enhancer
		manufacturer = O.M.B. Demolition Enterprises
		description = The TT18-A Stability Enhancer uses ground-breaking fastening technology to significantly increase the stability of spacecraft during the pre-launch phase. While OMB Demolition has been criticized in the past for using "big fancy words for a rocket holder" in their description of their device, none can say the TT18 series doesn't deliver rock-solid clamping action, as advertised. The owner's manual strongly suggests these devices be placed on the bottommost section of the spacecraft, and activated as soon as the engines are lit, for optimal de-clamping performance.
		attachRules = 0,1,0,1,0
		mass = 0.1
		dragModelType = default
		maximum_drag = 0.2
		minimum_drag = 0.2
		angularDrag = 2
		crashTolerance = 100
		maxTemp = 2500
		fuelCrossFeed = False
		explosionPotential = 0.1
		breakingForce = 150
		breakingTorque = 150
		stageOffset = 0
		childStageOffset = 0
		bulkheadProfiles = srf
		tags = clam hold )pad rocket stabil tower
		MODULE
		{
			name = ModuleTestSubject
			useStaging = True
			useEvent = False
			situationMask = 4
			useProgressForBodies = False
			usePrestigeForSit = False
			CONSTRAINT
			{
				type = SITUATION
				value = 4
				body = _Home
			}
			CONSTRAINT
			{
				type = SITUATION
				value = 0
				body = _NotHome
			}
			CONSTRAINT
			{
				type = REPEATABILITY
				value = ONCEPERPART
			}
		}
		MODULE
		{
			name = ModuleAnimateGeneric
			animationName = RestockLaunchClamp_Extend
			startEventGUIName = Extended
			endEventGUIName = Clamp Extension
			actionGUIName = Extend Clamp
			allowDeployLimit = true
			revClampDirection = false
			revClampSpeed = true
			revClampPercent = true
			eventAvailableFlight = false
			eventAvailableEVA = false
		}
		MODEL
		{
			model = ReStock/Assets/Structural/restock-launchclamp-1
		}
		MODULE
		{
			name = ModuleRestockLaunchClamp
			trf_towerPivot_name = obj_girdercap
			trf_towerStretch_name = obj_stretch
			trf_towerGirder_name = obj_girder
			trf_towerYoke_name = obj_yoke
			trf_anchor_name = obj_ground
			trf_animationRoot_name = restock-clamp-1
			anim_decouple_name = RestockLaunchClamp_Deploy
		}
		MODULE
		{
			name = GeometryPartModule
		}
		MODULE
		{
			name = FARAeroPartModule
		}
		MODULE
		{
			name = FARPartModule
		}
		MODULE
		{
			name = ProcessController
			resource = _ECGen
			title = Power supply
			capacity = 1.0
			running = true
			toggle = false
		}
		MODULE
		{
			name = PlannerController
			title = generator
			considered = false
		}
		MODULE
		{
			name = ModulePartInfo
			originalPartName = launchClamp1
		}
	}
}

```

**Comment by Gordon-Dry** [comment]
I pull this PR back because the issue is the other way around:
The fact that the part "launchClamp1" is treated like this
```
@PART[launchClamp1]:NEEDS[ProfileDefault]:FOR[KerbalismDefault]
{
  MODULE
  {
    name = ProcessController
    resource = _ECGen
    title = #KERBALISM_PowerSupply_title//Power supply
    capacity = 1.0
    running = true
    toggle = false
  }

  !MODULE[ModuleGenerator] {}
}
```
https://github.com/Kerbalism/Kerbalism/blob/df311ab026cc67bdd1b8e25652b775c15e225840/GameData/KerbalismConfig/Profiles/Default.cfg#L1294

is the issue.

The planner does always show thje EC/s usage in VAB, also when I toggle off the button "Simulate generator in planner".

I need to revert the mistake in Default.cfg and revert my commits.

**Comment by gotmachine** [comment]
Dev is Kerbalism 4.0 which has a completely different config format.
If you want to submit PRs for 3.x do them against master

**Pull request closed without merging**
