### PR TITLE
Russian localization, about 40% completed 

### PR DESCRIPTION
**Pull request by Argiziont**
Still working with this loc

### CODE REVIEW

**Comment by Unyo13** [comment]
I have more complete version. Should I add the file or can I edit by rows?

**Comment by Argiziont** [comment]
> I have more complete version. Should I add the file or can I edit by rows?

As u want,  u could edit my rows.

**Comment by Romsik788** [comment]
I recommend that you translate from version 4.0. For there are many changes.

**Comment by Argiziont** [comment]
> I recommend that you translate from version 4.0. For there are many changes.

If we could get access to translation file we'll separate work and do translation faster and more reliable.

**Comment by Unyo13** [comment]
Here is my version. An important issue - #KERBALISM_UI_dontcare should be translated shorter to fit the window.
[ru.zip](https://github.com/Kerbalism/Kerbalism/files/4747740/ru.zip)

**Comment by Unyo13** [comment]
Found the dev version, seems to be based on my translation. Please, inform me if any changes needed. There is a plenty of hardcoded strings in 3.9.

**Comment by Romsik788** [comment]
@Unyo13 save your strength and nerves for version 4.0 ;) There I think there will be a lot of work. In version 3.9 nothing else needs to be changed.

**Pull request closed without merging**
