### PR TITLE
Support USFuelCellMedium

### PR DESCRIPTION
**Pull request by lordcirth**
Didn't really test this, but it's just a copy-paste with some numbers changed.

### CODE REVIEW

**Comment by UsernamesAreAlwaysTaken** [comment]
needs testing. will do when i have the time.

**Comment by UsernamesAreAlwaysTaken** [comment]
oops.

**Comment by SirMortimer** [comment]
Don't forget to update CHANGELOG.md, please

**Comment by lordcirth** [comment]
Ok, I think this is good. Please excuse the force-pushes; I'm bad at git.

**Pull request merged**
