### PR TITLE
EC Balancing Tweaks

### PR DESCRIPTION
**Pull request by Breach-Candy**

### CODE REVIEW

**Comment by SirMortimer** [comment]
There is now a conflict in SoundingRockets.cfg ... (don't know  can you take a look at that?

**Comment by Breach-Candy** [comment]
Sure.

**Comment by UsernamesAreAlwaysTaken** [comment]
Conflict resolved. Waiting for Mr Travis to do his job.

**Comment by Breach-Candy** [comment]
Thanks.

**Pull request merged**
